//Add your code below
//The class name correct-answer is added to one of the answers
var questions = {
    questionText: "",
    answers: [
      { text: "", isCorrect: true/false, className: "" },
      { text: "", isCorrect:true/false, className: "" },
      { text: "", isCorrect: true/false, className: "" },
      { text: "", isCorrect: true/false, className: "" },
    ],
  questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
      { text: "", isCorrect: true/false, className: "" },
      { text: "", isCorrect:true/false, className: "" },
      { text: "", isCorrect: true/false, className: "" },
      { text: "", isCorrect: true/false, className: "" },
    ],
  questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
      { text: "", isCorrect: true/false, className: "" },
      { text: "", isCorrect:true/false, className: "" },
      { text: "", isCorrect: true/false, className: "" },
      { text: "", isCorrect: true/false, className: "" },
    ],
  questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
      { text: "", isCorrect: true/false, className: "" },
      { text: "", isCorrect:true/false, className: "" },
      { text: "", isCorrect: true/false, className: "" },
      { text: "", isCorrect: true/false, className: "" },
    ],
  questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
    questionText: "",
    answers: [
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect:true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
        { text: "", isCorrect: true/false, className: "" },
    ],
        }

  